allowBuilds:
  '@prisma/engines': true
  esbuild: false
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - msw
  - prisma
